export const ORBITAL_CANVAS = {
  width: 1440,
  height: 780,
};

export const ORBITAL_PLANETS = [
  {
    id: "cambridge",
    label: "CAMBRIDGE",
    texture: "/images/hero/planetas/textura-cambridge.webp",
    left: 823,
    top: 95,
    width: 128,
    height: 127,
    orbitDiameter: 127,
    orbitRadius: 91,
    orbitDuration: 8,
    orbitArc: 95,
    fontSize: 16.5,
    glow: "rgb(64 224 184 / 18%)",
    floatAmplitude: 5,
    floatDuration: 6.2,
  },
  {
    id: "ihs",
    label: "INTERNATIONAL HIGH SCHOOL",
    texture: "/images/hero/planetas/textura-ihs.webp",
    left: 920,
    top: 278,
    width: 142,
    height: 143,
    orbitDiameter: 142,
    orbitRadius: 107,
    orbitDuration: 10,
    orbitArc: 180,
    fontSize: 11,
    glow: "rgb(92 218 255 / 22%)",
    floatAmplitude: 4,
    floatDuration: 6.8,
  },
  {
    id: "rayados",
    label: "RAYADOS",
    texture: "/images/hero/planetas/textura-rayados.webp",
    left: 1132,
    top: 95,
    width: 147,
    height: 147,
    orbitDiameter: 147,
    orbitRadius: 105,
    orbitDuration: 8,
    orbitArc: 80,
    fontSize: 21,
    glow: "rgb(92 218 255 / 18%)",
    floatAmplitude: 6,
    floatDuration: 6.4,
  },
  {
    id: "craft",
    label: "CRAFT",
    texture: "/images/hero/planetas/textura-craft.webp",
    left: 1173,
    top: 371,
    width: 145,
    height: 145,
    orbitDiameter: 145,
    orbitRadius: 87,
    orbitDuration: 9,
    orbitArc: 65,
    fontSize: 24,
    glow: "rgb(255 174 42 / 12%)",
    floatAmplitude: 5,
    floatDuration: 7,
  },
  {
    id: "aula-feel",
    label: "AULA FEEL",
    texture: "/images/hero/planeta-Feel.png",
    left: 551,
    top: 421,
    width: 143,
    height: 137,
    orbitDiameter: 143,
    orbitRadius: 96,
    orbitDuration: 9.5,
    orbitArc: 105,
    fontSize: 18,
    glow: "rgb(80 190 255 / 16%)",
    floatAmplitude: 5,
    floatDuration: 6.6,
  },
];
